---
title: "Problem Set 7 - Dash"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(broom)
library(shiny)

```

Inputs {.sidebar}
-----------------------------------------------------------------------

Select the quality of the diamonds you want

```{r}
 selectInput("carat", label = h3("Carat"), 
    choices = list("1.0" = 1, "1.5" = 1.5, "2.0" = 2, "2.5" = 2.5), 
    selected = 1)

selectInput("clarity", label = h3("Clarity"), 
    choices = list("SI1" = "SI1", "VS2" = "VS2", "SI2" = "SI2",
                   "VS1" = "VS1", "VVS2" = "VVS2", "VVS1"="VVS1"), 
    selected = "SI1")

selectInput("cut", label = h3("Cut"), 
    choices = list("Fair" = "Fair", "Good" = "Good", "Very Good" = "Very Good",
                   "Premium" = "Premium", "Ideal" = "Ideal"), 
    selected = "Good")

selectInput("color", label = h3("Color"), 
    choices = list("D" = "D", "E" = "E", "F" = "F", "G" = "G", "H" = "H", 
                   "I" = "I", "J" = "J"), 
    selected = "E")


# clarity <- reactive(input$clarity)
# cut <- reactive(input$cut)
# color <- reactive(input$color)

```

Predict your diamond's price: (TBD)

   
Row
-------------------------------------

```{r}

diamonds %>% 
    filter(carat < 3) %>% 
    lm(price ~ carat + clarity + cut + color + carat:clarity + carat:color + carat:cut, .) -> fit_1

new_row = data.frame(carat =0.84,clarity="VS2", cut="Good", color="G")

# predict(fit_1, new_row)

```


    
### Price & Carat
    
```{r}

diamonds %>% 
    filter(carat < 3) %>% 
    ggplot(aes(x=carat, y=price)) + 
    geom_point(alpha = 0.5, size = 2, color = "#004D43") + 
    stat_smooth(method="lm") + 
    ggtitle("Relationship between diamonds carat and price") +
    labs(x="Carat",y="Price")

```
   
### Chart 2: Price & Cut

```{r}

diamonds %>% 
    ggplot(aes(color, price)) + 
    geom_boxplot(outlier.shape = NA, width  = 0.5, alpha = 0.7, color="#4C4C4C", notch = T) + 
    coord_flip() + 
    geom_point(color = "#004D43", alpha = 0.2, size = 1) + 
    labs(x="Color",y="Price")

```

   
Row
-------------------------------------
    
### Chart 2: Price & Clarity
    
```{r}

diamonds %>% 
    ggplot(aes(cut, price)) + 
    geom_boxplot(outlier.shape = NA, width  = 0.5, alpha = 0.7, color="#4C4C4C", notch = T) + 
    coord_flip() + 
    geom_point(color = "#004D43", alpha = 0.2, size = 1) + 
    labs(x="Cut",y="Price")

```
    
### Chart 3

```{r}

diamonds %>% 
    ggplot(aes(clarity, price)) + 
    geom_boxplot(outlier.shape = NA, width  = 0.5, alpha = 0.7, color="#4C4C4C", notch = T) + 
    coord_flip() + 
    geom_point(color = "#004D43", alpha = 0.2, size = 1) + 
    ggtitle("Relationship between diamonds price and different cut") +
    labs(x="Clarity",y="Price")

```

